### ISSUE TITLE
INDEX doesn't accept labels with offsets

### ISSUE THREAD

**Issue by davidgiven** [virtualagc/virtualagc#1071] opened 2019-07-20 18:32 UTC
This syntax:

    INDEX LABEL + 1

...is rejected with a 'Fatal Error: Index is not an address' error.

There seems to be nothing special about the INDEX encoding, so this seems an oversight rather intentional --- if `TC LABEL + 1` works, I'd expect the above to work.

**Comment by rburkey2005** [comment] 2019-07-20 19:10
Just by way of explanation, yaYUL was designed only to assemble the syntax found in existing AGC source code, and if this syntax doesn't appear in any existing AGC source code, it would likely never have been added to yaYUL.  So I'm not sure I would regard it either as an error or as an oversight. Unlike an assembler that would be designed from scratch today, yaYUL isn't really intended to make things easier for you when you do things that are unintended, but rather to force you to live under the same constraints as the original developers.  :smile:

With that said, what I'm getting at is that the correct answer is that yaYUL should accept the syntax if the original assemblers YUL or GAP would have done so, and reject it otherwise.  We didn't have the source for YUL when yaYUL was written, but do now.  I'm not familiar with the original YUL source enough to know, but I wonder if @jimlawton can tell us what YUL would have done in this situation?

Until we know one way or another, @davidgiven, you could just add an extra label (called, say, "LABEL+1") at LABEL + 1, and then use INDEX LABEL+1.  Though I'm sure you knew that perfectly well already.

**Comment by davidgiven** [comment] 2019-07-20 21:19
The context is that I just ported a compiler to it, and found all kinds of rough edges, which I'm currently working through trying to make reproducible. (Including one yaAGC crash. Not sure what was going on there.) What I was doing was doing pointer derefences, so syntax like `INDEX ptrval; CA 0`, and from the architecture, I don't think the authors ever used pointers! So, yes, this is definitely non-standard. http://cowlark.com/2019-07-20-cowgol-agc/

I didn't actually think of defining a new label, d'oh! It'd be as easy as `X = LABEL + 1; INDEX X`, too...

**Comment by rburkey2005** [comment] 2019-07-20 22:20
@davidgiven That's a pretty fab idea  ... and the idea of writing a lunar lander game _using_ your compiler, to actually be run on the AGC is doubly fab.  It's so fab it's faboo!  And your writeup actually already says the things I said in my comment.

I do hope, though, that most of the things you end up taking issue with can ultimately be worked around rather than forcing changes to the assembler.  At least in the short term.  The issue is that everyone who has worked on the yaYUL code in the past (including particularly myself) is pretty busy on other things right now, so it might take a problem as serious as generating incorrect output rope images for known-good source-code syntax to force somebody (me!) to get off their duff long enough fix it.

I'll keep my fingers crossed and await your conclusions regarding the other issues your writeup mentions.

**Comment by thewonderidiot** [comment] 2019-07-22 00:15
Neat project! I think, though, that you may be getting a cryptic error message that's masking whatever the true problem is. There's a lot of places in the original code where words of the form `INDEX LABEL +1` is used, and yaYUL assembles it for us fine -- for example, here: https://github.com/virtualagc/virtualagc/blob/master/Luminary099/IMU_COMPENSATION_PACKAGE.agc#L54

In the little snippet you've posted there's a space between the `+` and the `1`, which might aggravate yaYUL's tokenization. Are you generating those spaces, and does it work if you omit them?

**Comment by rburkey2005** [comment] 2019-07-22 11:26
D'oh!  Mike is right, obviously.  I got sidetracked in my thinking by the fact that "LABEL+1" is actually a valid variable name ... and by staring at LVDC assembly language solidly for the last week ... and any other excuse you can think of that doesn't involve me must being stupid.  :smile:  The syntax should have been "INDEX LABEL +1".

I'm going to close this issue.

**Closed by rburkey2005** 2019-07-22 11:26 UTC

**Comment by davidgiven** [comment] 2019-07-22 12:28
If a space is required after `LABEL` to prevent `LABEL+1` being treated as a single identifier, then surely a space would be required after the `+` to prevent `+` being parsed as a single identifier?

If `LABEL +1` is parsed as a valid addition operation, then why isn't `LABEL + 1` parsed the same way?

**Comment by rburkey2005** [comment] 2019-07-22 12:34
I didn't invent the language.  That's the way they did it.  :smile:

Perhaps you shouldn't think of it as an arithmetical expression.  It's not that you're _adding_ 1 to LABEL.  It's that "+1" is an _offset_ to "LABEL".  The syntax of this requires 2 fields:  One for the operand (LABEL) and one for the offset to it (+1).

**Comment by davidgiven** [comment] 2019-07-22 12:57
That makes sense; but can we have this spelt out in the documentation? This isn't mentioned anywhere.

**Comment by rburkey2005** [comment] 2019-07-22 13:08
I'll think about it how to do that.

**Comment by davidgiven** [comment] 2019-07-27 22:56
Oh, yeah, I completely forgot to say, earlier: `CAE label + offset` (with a space) is accepted, which was why I was surprised that `INDEX` didn't support it.
