### ISSUE TITLE
The Program Crashed.....

### ISSUE THREAD

**Issue by NickDeBeenAIE** [virtualagc/virtualagc#1177] opened 2022-08-04 03:44 UTC
Well, the title says it all really. I can't give you an entire output from a VM's console so...

It appears that I'm completely stuck.

Heres the terminal's final output (typed manually):

``mv: cannot stat 'MAIN.agc.symtab" : No such file or directory``
``make[1] : *** [../Makefile.inc:104: Luminary099.symtab] Error 1``
``make[1] : Leaving directory '/home/theroyalau/Desktop/VirtualAGC/Luminary099'``
``make: *** [Makefile:533: Luminary099] Error 2``

This took a long time to type.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 04:05
I forgot to install `build-essentials``, so I'll close my own issue.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 04:11
Hows this for you, the program crashes when a Sim is started of either system.

**Comment by rburkey2005** [comment] 2022-08-04 10:29
> Hows this for you, the program crashes when a Sim is started of either system.

Please, when you report problems, include precise details about what you did to initiate the situation, and precise observations about what you observed.  I don't know which "program" you're referring to here (the VirtualAGC GUI program? the AGC simulation?), I don't know what you mean by "crashed" (it froze up your system? it appeared on the screen but did nothing? it just disappeared?), and I don't have much of a clue what you mean by "either system". 

As it stands, what you _could_ mean is that you ran the VirtualAGC GUI, used it to start a simulation of the AGC + DSKY, and when the DSKY appeared on the screen the VirtualAGC GUI disappeared.  _That_ is exactly what's designed to happen.  After you close the DSKY, the VirtualAGC GUI reappears.

If that's what you meant, it's perfectly normal and is exactly what should have happened.  It's not a bug.  If that's _not_ what you meant, then you'll have to provide more of the kinds of details I asked for.  Perhaps a screenshot of what the VirtualAGC window looked like when you initiated the simulation, so that I can see what options you had set would be nice.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 10:43
It just crashed on the Sims launch, I mean, the DSKY crashed as well.

The programs UI also crashed.

What I meant by systems, is the AGS, and the AGC.

What am I doing wrong to cause the program to crash?

This is beyond me.

Core Rope memory is also missing, the AGC requires that to be in its
different operating systems folders i.e., Luminary099.

I don't know where to find that either.

I try to load a .core and theres none in any of the directories.

**Comment by rburkey2005** [comment] 2022-08-04 11:32
I'll tailor my suggestions based on the assumption you're still trying to use WSL in much the same setup you described in other bug reports.  If you've given up on WSL and are using a different setup (such as our recommended VM), then you'll have to modify the folder names accordingly.

So, I _assume_ you're running the VirtualAGC GUI as follows:

```
cd /mnt/c/users/nick/desktop/VirtualAGC/Resources
../bin/VirtualAGC
```

The sole purpose of the VirtualAGC GUI program is to take the various options you select and to create a bash script called "simulate" from them, and then to run that bash script.  That's great when it works, but since it hides details such as error messages from you, it's not so great if you want to debug a failure.

So do the following two things:  **First**, find the "simulate" script (it should be in /mnt/c/users/nick/desktop/VirtualAGC/Resources if my guesses about your setup are corred), and post its entire contents here.

**Second**, do this:

```
cd /mnt/c/users/nick/desktop/VirtualAGC/Resources
./simulate
```

This will run the identical simulation you had been trying to run, except that the VirtualAGC GUI will never appear.  The simulation will presumably crash in the same way you described above.  But _now_ there will now presumably be messages in your command-line window that may provide some detail about what happened.  Cut-and-paste everything in your command-line window (including the line "`./simulate`" down to the next time a prompt appears) here, so that I can see them.

For example, when I do this in a working Virtual AGC installation, I see command-line messages like the following after closing the DSKY window:

```
virtualagc@VirtualAGC-runtime:~/VirtualAGC/Resources$ ./simulate
rm: cannot remove ‘LM.core’: No such file or directory
rm: cannot remove ‘CM.core’: No such file or directory
Apollo Guidance Computer simulation, ver. 2017-06-19, built Aug 31 2017 10:18:23
Copyright (C) 2003-2009 Ronald S. Burkey, Onno Hommes.
yaAGC is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Refer to http://www.ibiblio.org/apollo/index.html for additional information.
yaDSKY2 Apollo DSKY simulation, ver NVER, built Aug 31 2017 10:19:12
Copyright 2009 by Ronald S. Burkey
Refer to http://www.ibiblio.org/apollo/index.html for more information.
Arg 1 = "--cfg=LM.ini"
Arg 2 = "--port=19797"
Hostname=localhost, port=19797
yaDSKY is connected.
Adding socket 13 on port 19797
GREP=grep
Scanning for program status of processes 6123 6122
Core-dump file "LM.core" created.
Removing socket 13
Process 6122 has terminated.
Bye! Shutting down the simulation.
../bin/SimStop: 67: kill: No such process

virtualagc@VirtualAGC-runtime:~/VirtualAGC/Resources$ 
```

As for the ".core" file, that's created periodically by a running simulation.  It won't exist if you haven't succeeded in running the simulation for a significant length of time.  So its absence is not surprising, and is not a problem.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 11:43
I'm using VMWare Workstation Player, so your dead wrong on your assumption.

I'm not using WSL, its f***ing useless, and I think I previously mentioned
that I turned that feature off.

**Comment by rburkey2005** [comment] 2022-08-04 11:53
> I'm using VMWare Workstation Player, so your dead wrong on your assumption.

Look ... I'm dead wrong in my assumptions because you don't provide me with the details up front. As I keep requesting that you do. You give me no choice except to make assumptions.  Furthermore, you also said that you had posted bug reports to Microsoft about WSL, and for all I know, you could have gotten WSL working in the meantime.  I'd further observe that inflammatory remarks seldom make people enthusiastic about assisting you.

Now ... If you are running some form of Linux in your VM, then the appropriate folder name is ~/VirtualAGC/Resources.  Yes, I know that's an assumption on my part that you're running Linux in your VM.  So please follow the two suggestions from my previous post, but with corrected folder names.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:03
I'm not a professional programmer, so, please expect only minor details.

![image](https://user-images.githubusercontent.com/60248725/182842203-801e2395-61ee-4210-bde1-0c38eabe4f23.png)

You'll need to cut the image in half, but now you know whats happening, and it isn't my VM as it has plenty of performance.

**Comment by rburkey2005** [comment] 2022-08-04 12:28
Well, what I asked for is the contents of the .../Resources/simulate file, and for the messages from the command-line window when you run the .../Resources.simulate file.  I would like to see those things.

The screenshot is nevertheless interesting.  It at least says that the AGC simulation had indeed been running and doing something, at least for a while, and that it was able to connect to the telemetry simulation.  So that's all good.  It may indicate that it's the DSKY which is failing. In addition to the two things I asked for above, you might

```
cd ~/VirtualAGC/Resources
../bin/yaDSKY2
```

and tell me if the DSKY appears and/or crashes.  (It won't _do_ anything if it does appear.  It's just a test.)

By the way, it has been perhaps 10 years now since I used vmware, but I expect that somewhere on its menu it should have an option for taking a screenshot of just the VM.  (For example, in virtualbox, which is what I use rather than vmware, the main menu has a View/TakeScreenshot function.)  You might find that a little more convenient than a monster screenshot of your entire host system.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:31
Ok, well, ``-bash: ./simulate: No such File or Directory``

![image](https://user-images.githubusercontent.com/60248725/182847462-e93b4d43-2a41-425b-884e-298d36a284af.png)

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:32
Again, wrong directory spoken:

``-bash: ~/VirtualAGC/Resources: No such file or directory``

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:35
Wow, ok, yaDSKY2 did not crash:

![image](https://user-images.githubusercontent.com/60248725/182848299-a3dbdee8-dc79-4103-943d-516f185d906d.png)

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:40
Here's the output from the terminal (again, typed manually):

``yaDSKY2 Apollo DSKY Simulation, ver NVER, built Aug 4 2022 13:31:41``
``Copyright 2009,2017,2022 by Ronald S. Burkey``
``Refer to http://ibiblio.org/apollo/index.html for more information``
``Hostname=localhost, port=19697``

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:46
Ok, connected a flight stick, yet still no simulation.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:47
Please see below:

![image](https://user-images.githubusercontent.com/60248725/182850581-1169b74f-d06f-498c-8d13-0de20b9ec8ca.png)

**Comment by NickDeBeenAIE** [comment] 2022-08-04 12:54
> By the way, it has been perhaps 10 years now since I used vmware, but I expect that somewhere on its menu it should have an option for taking a screenshot of just the VM. (For example, in virtualbox, which is what I use rather than vmware, the main menu has a View/TakeScreenshot function.) You might find that a little more convenient than a monster screenshot of your entire host system.

VMWare does not have this in Player. It does however in Pro.

**Comment by rburkey2005** [comment] 2022-08-04 13:02
> (again, typed manually)

It may have a shared-clipboard feature for cut-and-paste.  That would at least prevent you from having to type everything or resorting to screenshots for everything.  In virtualbox, the shared clipboard has to be enabled in the settings or main menu.  Here's [a link describing it](https://smallbusiness.chron.com/can-run-32bit-xp-virtualbox-64bit-windows-7-host-81755.html), though it doesn't mention Player vs. Pro.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 13:03
> > (again, typed manually)
> 
> It may have a shared-clipboard feature for cut-and-paste. That would at least prevent you from having to type everything or resorting to screenshots for everything. In virtualbox, the shared clipboard has to be enabled in the settings or main menu. Here's [a link describing it](https://smallbusiness.chron.com/can-run-32bit-xp-virtualbox-64bit-windows-7-host-81755.html), though it doesn't mention Player vs. Pro.

Exactly, which is why copying and pasting from Player is not supported unless the user buys a Pro license.

**Comment by rburkey2005** [comment] 2022-08-04 13:06
Pro tip for the future: [VirtualBox](https://www.virtualbox.org/) is full-featured (for any conceivable amateur purpose at least) and free.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 13:10
> Pro tip for the future: [VirtualBox](https://www.virtualbox.org/) is full-featured (for any conceivable amateur purpose at least) and free.

Sounds very rookie to me, I only use VMWare, as it can take full advantage of your systems performance.

Oracle VirtualBox is hard limited to 256MB of VRAM.

It is also VERY slow compared to VMWare. Plus, VMWare does allow you to allocate more RAM if need be. The VM's Hardware can be fully customized, VirtualBox does not have very much of customization in comparison.

**Comment by rburkey2005** [comment] 2022-08-04 13:25
> Oracle VirtualBox is hard limited to 256MB of VRAM
>
> It is also VERY slow compared to VMWare. Plus, VMWare does allow you to allocate more RAM if need be. The VM's Hardware can be fully customized, VirtualBox does not have very much of customization in comparison.

No comment, other than that these kinds of customizations might be useful for high-end gaming systems or for system administrators with very specific needs, but not for running VirtualAGC.  Oh, well, and the "VERY slow" thing has no relation to any experience of mine in using both.  Personally, I run many of these VMs and seldom if ever have allocated more then 32MB for VRAM.  It's probably more than I need.  And I think you can have both VMWare and VirtualBox installed at the same time.  But it's no skin off my nose, and you're entitled to your own choices in these matters, so there's no need to refute me on a point by point basis (or at all).

But back to the issue at hand.  You don't say how you're running VirtualAGC.  If you're running it from a command line, then 'simulate' _has_ to be in the same Resources folder from which you're typing the commands; there's simply no other possible way you could be seeing any of the simulation stuff on the screen, even momentarily.

Therefore, I can only suppose you're running VirtualAGC from the desktop icon, and that the icon is using a Resources folder other than the Resources folder you're looking at when you say that 'simulate' doesn't exist.  Please left-click the desktop icon for VirtualAGC and select "Properties".  You should be able to see the exact command-line which the icon executes along with the (possibly blank) working directory it uses.  Tell me what those are.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 13:38
Nope, I'm running the program quite literally from terminal.

Like I said:

``-bash: /Resources/simulate: No such file or directory``

I can be safe to say, its actually referring to the simulation file itself.

While I can run ``./simulate`` from /bin, it opens for a very brief period
of time and crashes giving no indication of what went wrong other then a
process error of 8066.

This is also alongside of other gibberish that shows in the terminal.

I'm just saying what the final output of the terminal is.

**Comment by rburkey2005** [comment] 2022-08-04 14:15
>  ``-bash: /Resources/simulate: No such file or directory``

The file I'm interested in is "~/VirtualAGC/Resources/simulate", not "/Resources/simulate".

I need you to edit that file using whatever built-in text editor your Linux system has.  You may possibly find it in Accessories in the menu.  Or not.  But there's some way to invoke a text editor.  Near the end of the file, you should find lines that look something like

```
export PIDS
../bin/SimStop
```
What I want you to do is to add a line, as follows:

```
export PIDS
ps auxww | grep '\.\./bin/'
../bin/SimStop
```

Then run 'simulate' again.

Please give me a screenshot of all its messages, regardless of whether or not it seems like gibberish.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 20:56
The directory is still wrong on your end.

``/home/theroyalau/Desktop/VirtualAGC/VirtualAGC/temp/lVirtualAGC/Resources``

**Comment by NickDeBeenAIE** [comment] 2022-08-04 20:58
``-bash: ~/VirtualAGC/Resources/simulate: No such file or directory``

**Comment by NickDeBeenAIE** [comment] 2022-08-04 21:00
![Screenshot from 2022-08-05 06-30-05](https://user-images.githubusercontent.com/60248725/182951769-1de08e69-c119-4792-bb29-ed6f4457b9d0.png)

See what I mean?

**Comment by rburkey2005** [comment] 2022-08-04 21:10
![image](https://user-images.githubusercontent.com/60248725/182850581-1169b74f-d06f-498c-8d13-0de20b9ec8ca.png)

Here's the _previous_ screenshot you sent me, when you actually ran `simulate`.  It clearly shows ~/VirtualAGC/Resources, both in the window title and in the command-line prompt.  It (`simulate`) must have been in that directory at that time, or else you couldn't have been running it.

But frankly, I don't care _where_ it is, all I care about is that in the directory you're actually using to run the thing, you do the edit I asked you to make, run `simulate` again, and tell me what the messages are.

**Comment by rburkey2005** [comment] 2022-08-04 21:18
> See what I mean?

I asked you to _run_ `simulate`, not to `cd simulate`.  The latter would be a command to change into a folder called "simulate", and bash is correct, there is no such thing.  Rather, "simulate" is the name of a bash script, and the way you run it is with the command

`./simulate`

**Comment by NickDeBeenAIE** [comment] 2022-08-04 21:20
The bash script never gets created.

I cannot find it in any directory.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 21:33
> If you're running it from a command line, then 'simulate' has to be in the same Resources folder from which you're typing the commands; there's simply no other possible way you could be seeing any of the simulation stuff on the screen, even momentarily.

``make install`` did not put the ``./bin/simulate`` file in the Resources folder, I have checked the directory and never found it, I did however find it the ``/bin`` directory, which in my case is where the scripts are loaded from.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 21:42
Ok, I tried again to run a simulation, so here's a HTML of its output.

<pre>./simulate
rm: cannot remove &apos;LM.core&apos;: No such file or directory
rm: cannot remove &apos;CM.core&apos;: No such file or directory
LM Abort Guidance System simulation, ver. 2022-07-17, built Aug  4 2022 11:43:00
(c)2005,2009 Ronald S. Burkey.
Refer to http://www.ibiblio.org/apollo for additional information.
Loaded 010000 (octal) 18-bit values.
Address 06000 contains the value 706177, opcode 70
./simulate: 15: wish: not found
Apollo Guidance Computer simulation, ver. 2022-07-17, built Aug  4 2022 11:42:59
Copyright (C) 2003-2009 Ronald S. Burkey, Onno Hommes.
yaAGC is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Refer to http://www.ibiblio.org/apollo/index.html for additional information.
yaACA3 Apollo ACA simulation, ver NVER, built Aug  4 2022 13:31:45
Copyright 2009 by Ronald S. Burkey
Refer to http://www.ibiblio.org/apollo/index.html for more information.
yaDSKY2 Apollo DSKY simulation, ver NVER, built Aug  4 2022 13:31:41
Copyright 2009,2017,2022 by Ronald S. Burkey
Refer to http://www.ibiblio.org/apollo/index.html for more information.
Arg 1 = &quot;--half-size&quot;
yaDEDA2 Apollo DEDA simulation, ver NVER, built Aug  4 2022 13:31:38
Copyright 2009 by Ronald S. Burkey
Refer to http://www.ibiblio.org/apollo/index.html for more information.
Arg 1 = &quot;--half-size&quot;
Arg 2 = &quot;--cfg=LM.ini&quot;
Arg 3 = &quot;--port=19797&quot;
Hostname=localhost, port=19797

yaTelemetry build Aug  4 2022 13:31:48, Copyright 2009,2022 Ronald Burkey
For more information, consult http://www.ibiblio.org/apollo.
     --delay=0
     --port=19800
     --ip=localhost
     --spacecraft=LM
     --font-size=8
     --undecorated
     --simple
     height=728
Hostname=localhost, port=19897
SDL library initialized.
Checking if can talk to joystick.
yaDSKY is connected.
yaTelemetry is connected.
yaDEDA2 is connected, socket=10.
Joystick controller model:  Thrustmaster T.16000M
Joystick axes are: #0 #1 #2 #3
Roll=+00	Pitch=+00	Yaw=+00
Connection to server established on socket 4
Adding socket 13 on port 19797
Adding socket 14 on port 19800
Adding socket 15 on port 19803
Adding socket 13 on port 19897
GREP=grep
Scanning for program status of processes 19082 19081 19080 19079 19078 19077 19076
Process 19081 has terminated.
Bye! Shutting down the simulation.
../bin/SimStop: 67: kill: No such process</pre>

**Comment by rburkey2005** [comment] 2022-08-04 22:21
> make install did not put the ./bin/simulate file in the Resources folder, I have checked the directory and never found it, I did however find it the /bin directory, which in my case is where the scripts are loaded from, as with SimStop

No comment.

The list of messages from this run of `simulate` is complete, rather than chopped off at the top as it was in the screenshot from the preceding time you managed to get `simulate` to run, and as a result, there is perhaps a clue in it.  Namely, it says

> ./simulate: 15: wish: not found

Typically this would mean that Tcl/Tk is not installed.  You don't say which Linux distribution you're using, but if it were Ubuntu, Mint, or Debian, I expect that

`sudo apt install tcl tk`

would probably install it for you.  If not, you need to research how to do that for your particular Linux distribution.  You can test whether it's installed by running

`wish`

from a command line.  Alternately, if you were to run the simulation from the `VirtualAGC` GUI (rather than by running `simulate` from a command line), you can uncheck the box that reads "AGC CPU Bus/Input/Output Monitor" since that's the only component of the system that uses Tcl/Tk. 

If this turns out to be the problem, be sure and tell me what Linux distribution you're using &mdash; both name _and_ version number &mdash; so that I can update the list of prerequisites on the installation page.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 22:26
Linux Mint 20.3 "Una", so this will no issue.

**Comment by rburkey2005** [comment] 2022-08-04 22:28
> Linux Mint 20.3 "Una", so this will no issue.

Do you mean that installing it will be no issue, or do you mean that it's already installed?

**Comment by NickDeBeenAIE** [comment] 2022-08-04 22:30
Installed without issue just as you sent that XD

**Comment by rburkey2005** [comment] 2022-08-04 22:31
It's curious that it wasn't already installed, as I seemed to have it by default on Mint 20.1 and Mint 21 (just earlier today!).  Well, it's easy to be confused about these things.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 22:36
What? Mint 21's out? Holy s***, I should ``mintupgrade upgrade``.

**Comment by rburkey2005** [comment] 2022-08-04 22:37
> Never mind, it has not been released yet.

So I found out, to my dismay.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 22:41
OH MY F***ING GOOD LORD I got the Sim running, and WOW that's a lotta gauges.

I'd like to load the self test program, how do you do that?

**Comment by rburkey2005** [comment] 2022-08-04 22:45
In the VirtualAGC GUI, among the "AGC Simulation Types" listed in the upper left, one of them is "Validation Suite".

**Comment by NickDeBeenAIE** [comment] 2022-08-04 22:56
Ok, I chose that, but it failed an assertion when I hit save on the right to send it to the AGC.

**Comment by NickDeBeenAIE** [comment] 2022-08-04 22:59
Second time lucky though, please advise on the Noun, then Verb of Prog 00 to begin testing.

**Comment by rburkey2005** [comment] 2022-08-04 23:05
[The instructions are here](https://www.ibiblio.org/apollo/download-old.html#Running_the_Validation_Suite).

**Comment by rburkey2005** [comment] 2022-08-04 23:06
It's not a very exciting program to look at.  [The only other things you can really do without a learning curve are described here](http://www.ibiblio.org/apollo/index.html#Quick_Start).

**Comment by NickDeBeenAIE** [comment] 2022-08-04 23:37
Aurora 12 simulation has no 9 digits in its code, I mean, the number 9 on the DSKY does not work.

**Comment by rburkey2005** [comment] 2022-08-04 23:59
You'll have to be a bit more specific, as I have no idea what you're trying to do.  Do you mean that you're trying to do something like 

`VERB 59`

or 

`NOUN 91`

on the DSKY?  If memory serves, early versions of the AGC software (such as Aurora 12) used only octal nouns, verbs, and program numbers, so only digits 0 through 7 are recognized in that kind of context.  Late software versions such as Artemis and Luminary began using decimal numbers (0-9) for those kinds of things as well.  You'd have to look at the specific mission requirements to really know.  So, no, without any idea of the context of your comment, I'd say _not_ broken.

Of course, if you were entering (say) a velocity into the DSKY, it would be a decimal number in either case.

At any rate, this seems to have little to do with the problem you reported.  Should it be closed now?

**Comment by NickDeBeenAIE** [comment] 2022-08-05 00:00
How do you open the LM DSKY? I tried ``./simulate`` using Aurora 12, but the CM DSKY opens.

**Comment by rburkey2005** [comment] 2022-08-05 00:05
The `VirtualAGC` GUI assigns the appropriate DSKY type when it creates the `simulate` file.  I'd suggest you let `VirtualAGC` do it rather than ask me to go read through the documentation.

_Without_ reading the documentation, though, it seems likely that since Aurora 12 was a very early program (in the general scheme of things), it likely used the same DSKY as the very early Colossus programs anyway.

**Comment by rburkey2005** [comment] 2022-08-05 00:09
By the way, here are the reference cards for [Aurora](http://www.ibiblio.org/apollo/Documents/Retread50AuroraSundialBCCards.pdf).  Recall that Aurora was not a flight program and was used for testing purposes.

**Comment by NickDeBeenAIE** [comment] 2022-08-05 00:20
Yeah, it looks like it uses Verbs only, or the Nouns weren't scanned properly.

**Comment by rburkey2005** [comment] 2022-08-05 00:25
If you're talking about the reference cards, both verb and noun codes are listed.  (They're on the same page.  One column that describes the function of the verb, one column that gives the numerical code from 00 through 77, and one column that describes the function of the noun with that code.)

**Comment by NickDeBeenAIE** [comment] 2022-08-05 00:32
I don't see Aurora 12's Noun's, just its Verbs, as the Noun's column is completely gone, it wasn't scanned properly.

**Comment by rburkey2005** [comment] 2022-08-05 00:46
Well, I don't know how to account for that.  I'm looking right at it, and I can see them.  Here, I've made a screenshot for you:

![AuroraVerbsNouns](https://user-images.githubusercontent.com/11841400/182978404-802cabcd-a81b-4320-81a2-8e370d074b45.png)

**Comment by NickDeBeenAIE** [comment] 2022-08-05 00:47
> Well, I don't know how to account for that. I'm looking right at it, and I can see them. Here, I've made a screenshot for you:
> 
> ![AuroraVerbsNouns](https://user-images.githubusercontent.com/11841400/182978404-802cabcd-a81b-4320-81a2-8e370d074b45.png)

You are seeing codes for the Verbs only.

**Comment by rburkey2005** [comment] 2022-08-05 00:50
No.  For example:

Code 20:  Verb=ILLEGAL, Noun=ICDU
Code 21:  Verb=LOAD COMP 1, Noun=PIPAS
Code 22:  Verb=LOAD COMP 2, Noun=New angles 1
 
And so on.  There was no reason to print two columns of identical numbers.  It's probably not the particular choice _I_ would have made, but it's what they did.

**Comment by NickDeBeenAIE** [comment] 2022-08-05 00:52
Every bit of software for AGC of any kind needs their Verbs first, then their Nouns, if I scroll down on sent PDF, I can see, for example, Sundance's Verb's and Nouns

**Comment by NickDeBeenAIE** [comment] 2022-08-05 00:54
Not even Retread 50's Noun's are showing if you take a look.

**Comment by NickDeBeenAIE** [comment] 2022-08-05 00:55
I am kindly referring to Retread 50's and Aurora 12's Noun numbers. Which is pretty much what I meant all along.

**Comment by rburkey2005** [comment] 2022-08-05 01:03
The code numbers shown on the reference cards for the verbs _and_ for the nouns are identical to what's in the Aurora source code.  If you prefer to interpret them as being missing, that's your right.

[But here are reference cards for a different version of Aurora which should make you happier](http://www.ibiblio.org/apollo/Documents/Aurora88SundialCCards.pdf):  The numbers are the same, but they printed two columns of them.  Perhaps other folks were confused about them too, and they rethought their printing format.

And now, I'm going to close this issue.  If you want to research the matter further, [our document library page](http://www.ibiblio.org/apollo/links2.html) is just brimming with these kinds of little details.

**Closed by rburkey2005** 2022-08-05 01:03 UTC
