### ISSUE TITLE
Luminary 131 not flight software?

### ISSUE THREAD

**Issue by indy91** [virtualagc/virtualagc#540] opened 2016-12-16 22:00 UTC
I started work on a Luminary131 padload worksheet and noticed a discrepancy between some addresses in the Erasable Assigments and the LM7 Padload document that is available. The table with the different versions (http://www.ibiblio.org/apollo/R700-3-Table4-11.jpg) would support this. The Luminary 131 we have is assembly no. 2021112-091, while the flown version is apparently no. 2021112-121. The first version was released in December 1969, and the last version in February 1970.

I originally started this issue because I wasn't sure about the versions, but now it seems very clear. I guess this info is probably useful for the Luminary page describing the different versions. I personally only have to be extra careful to get the pad load worksheet right.

**Comment by rburkey2005** [comment] 2016-12-16 22:03
Terrific!  As you may recall, one of Don Eyles's available listings is Luminary 131, but miserliness was definitely pushing it to the bottom of the desirability list in terms of paying for the scanning.  I'll inquire which one it is, and if it's -121, it might push it back nearer the top of the list.

**Comment by indy91** [comment] 2016-12-16 22:09
Yeah, would be great if that is the flown version. We won't really need it any time soon for NASSP, we barely have Luminary099 working and before trying Apollo 13 I will rather get Luminary069 ready.

**Comment by rburkey2005** [comment] 2016-12-16 22:15
Turns out I didn't need to ask.  In the email in which Don mentioned it, he specified that it was "Dec. 19, 1969".  :frowning_face: 

If only this were a perfect world, eh?

**Comment by rburkey2005** [comment] 2016-12-16 22:19
Though, of course, Luminary 131 never landed on the moon, anyway.  But a simulated mission would still be nice.  It looks like [LUMINARY Memo #129](http://www.ibiblio.org/apollo/Documents/LUM129-001.pdf) describes the change that resulted in the December version.  Perhaps a future memo describes the change for the February version.

**Comment by rburkey2005** [comment] 2016-12-16 22:24
I've sent Don an inquiry about additional memos, and explained our problem about the pad-load addresses.  We'll see what, if anything, he comes up with.

**Comment by indy91** [comment] 2016-12-16 22:37
What I discovered were some P66 related changes. At least on the erasable memory side P66 still seems to have been fairly similar to Apollo 11. 

And it looks like it even still has the separate landing programs: P65 for auto landing, P66 for the Rate of Descent program (used for all actual landings) and then P67 for a manual landing. Apollo 12 still had these and for Apollo 13 the automatic and manual modes were incorporated into P66. Our Luminary131 version stills seems to have the three programs.

It might be that the changes are all those mentioned in the GSOP R-567 section 5 page xi-a (yes, you read that right).

**Comment by thewonderidiot** [comment] 2016-12-17 09:42
Seeing this conversation jogged my memory that the Computer History Museum out here also has a Luminary 131 listing. But unfortunately, it looks like it too is from Dec 19, 1969 :-/
http://www.computerhistory.org/collections/catalog/102625929

**Comment by rburkey2005** [comment] 2016-12-17 10:43
I don't remember the context exactly, but Hugh pointed out to me that when they did this work, they weren't really considering _our_ convenience.  He seemed to find that more amusing than I did, but I can still :smile:.

**Comment by indy91** [comment] 2016-12-17 12:53
I mean, surely it would have been THEIR convenience to keep the flown version of the listing and not have the outdated version in personal collections and museums.

For me it's not too much of an inconvenience. I simply created two slightly differing versions of the padload worksheet, one based on the LM-7 padload document and one changed to fit our Luminary 131 version. No big deal. 

Would have been nice to have the Auto P66 feature for the Apollo 13 mission though. Is Apollo 14 one of the LGC versions that will become available? Potentially we would use that for Apollo 13 instead, if Luminary 131 Rev. 1 never becomes available.

**Comment by rburkey2005** [comment] 2016-12-17 13:58
My impression of these printouts is that (relatively speaking, and given that a _lot_ of people might have wanted them at the time even though they've discarded them in the intervening decades) it would simply have been too expensive and time-consuming to provide too many of them.  Consequently, what people have preserved is whatever copies they had been working on and were still sitting around on their desks, not the latest and greatest.  If, say, Luminary131/1 was the last version Don had worked on, then it's the last version he would have had in hand.

You can see that with some of the other developers, like Allan Klumpp, where he _thought_ he had the flown versions of Luminary 99 and Luminary 210 in his collection, but did not actually.  But even then, he told me he consulted his managers or whatever to get them to tell him what he had (and they were wrong!).

As to why everybody has the _same_ version of 131 now, the speculation is that the version we have is actually a mutilated reproduction of Don's copy anyway.  (The idea is that Hugh xeroxed Don's hardcopy and gave it to Jame Kernan, who gave it to David Craig, where it was scanned by Gary Neff, and then was expletive^H^H^H^H^H^H^H^H^Hreprocessed into illegibility by the HRST website.)  As far as to why the Computer History Museum has the same version, I can't say.  That may just be bad luck, or they may just have David Craig's xerox.

My pet theory is that Draper Labs has every version of everything sitting in their basement, but nobody at Draper will admit anything to me, so that may just be crazy talk.  The version of the Apollo 11 code in the MIT Museum certainly was given to them by Draper Labs.

**Comment by rburkey2005** [comment] 2016-12-17 14:01
And the same comments apply to all of the incomplete, out-of-date documents (like GSOPs) at the National Archives.  It was certainly my impression that there had been no concerted effort to preserve anything, and that somebody just went into all the old offices at some point, and just picked up whatever documents were left, and sent them to the National Archives rather than keeping them around to waste precious space ... like using the National Archives as a really fancy trash can.  Of course, impressions can be deceiving, and it might be interesting to know what the actual process was.

**Comment by rburkey2005** [comment] 2016-12-23 15:43
I don't have any idea what we can do about this anyway, other than hope a newer version pops up someday ... and of course updating the website to show that this isn't _quite_ the flown version.  Since I'm in the process of doing that very thing, I'm going to close this issue.

**Closed by rburkey2005** 2016-12-23 15:43 UTC
