### ISSUE TITLE
Decoding real AGC output

### ISSUE THREAD

**Issue by jumpjack** [virtualagc/virtualagc#1155] opened 2022-01-24 14:44 UTC
Can anybody help in decoding the output of the real AGC?

http://www.ibiblio.org/apollo/Documents/apollo_11_computer_words.pdf

Most of the tables headers are unreadable:

PAGE 1:
![immagine](https://user-images.githubusercontent.com/1620953/150803575-2723f09c-44ef-4f38-99a0-397edcf7f305.png)

My decoding attempt:

![immagine](https://user-images.githubusercontent.com/1620953/150803245-ee07eb75-bb27-46f7-b604-88c2e5ecdfc6.png)

Page 11:
![immagine](https://user-images.githubusercontent.com/1620953/150803527-c41037f7-4f71-40b3-a74c-ef4cd5039035.png)

My decoding attempt:
![immagine](https://user-images.githubusercontent.com/1620953/150803435-023a5a27-dce2-4ccb-985a-e0aadcb72fa5.png)

Page 13:

![immagine](https://user-images.githubusercontent.com/1620953/150803825-bf003bb4-0643-4242-b39a-90e9aa9a31e0.png)

My decoding attempt:
![immagine](https://user-images.githubusercontent.com/1620953/150803909-22eb480f-8dbb-4485-b25e-639f7dd5991f.png)

Does it exists a list of "elements" mentioned in these headers? 

Or maybe does it already exists a transcript of this document?

**Comment by thewonderidiot** [comment] 2022-01-25 07:52
This was a pretty recent find, and there's no transcript of it (although I would love for there to be one -- just haven't had the time). Each column in this document is one item on the Descent/Ascent Downlist, a set of 100 telemetry points that the LGC telemetered during the landing. In the code, that list is defined [here](https://github.com/virtualagc/virtualagc/blob/master/Luminary099/DOWNLINK_LISTS.agc#L277)... but it's encoded in a way that is tricky to follow, and doesn't really illustrate well what each point actually is. Section 2 of the GSOP for the mission is the best reference for this. While we don't have the one for Apollo 11, its descent/ascent downlist is almost identical to [the one for Apollo 13, which we do have the GSOP for](https://www.ibiblio.org/apollo/NARA-SW/R-567-sec2-rev8.pdf#page=117). The description of this particular downlist starts on page 117 of the PDF and continues on through page 122.

As far as your transcriptions go, I think you're mostly right. Most of these headers appear on multiple pages, so you can cross-reference. For example, the header on page 2 is identical to the one on page 1, but much more readable. I'd also recommend [viewing this document directly on the Internet Archive](https://archive.org/details/apollo_11_computer_words/mode/1up?view=theater), because the PDFs it generates, liked the one you linked, can be a bit over-compressed and harder to read.

![image](https://user-images.githubusercontent.com/94056/150933140-c9fac9a5-6b01-4dd6-a3dd-6410cda7c2b8.png)

This all looks right to me. All of this information comes out of the DSPTAB entries in the downlist.

![image](https://user-images.githubusercontent.com/94056/150933702-f7ac5937-c958-4ea5-821d-d2a51edfad1b.png)

The first two columns are "ALPHAR, ACCEL ABOUT Z BODY AXIS, ELEM 313", and "ALPHAQ,  ACCEL ABOUT Y BODY AXIS, ELEM 312". The next two columns start with "CSMMASS" and "LMMASS", and I think both say "ESTIMAT".

![image](https://user-images.githubusercontent.com/94056/150934298-19c84de6-1016-4441-91d6-5cab0cf626e9.png)

All looks right to me!

**Comment by jumpjack** [comment] 2022-01-25 09:11
Thanks, I studied a bit the GSOP document, but I don't understand how you did correlate elements numbers in the log to words number on page 136 and to DSPTAB values.

**Comment by rburkey2005** [comment] 2022-01-25 11:39
@jumpjack That's very curious!  I replied yesterday with the same info about section 2 of the GSOP, though without @thewonderidiot 's other helpful info :smile:.  But my comment doesn't seem to be here, even though my email client shows that I sent it.  Weird!  Did you actually receive it separately as email, or did it just disappear into limbo?

But I digress.  I wonder if the "element" numbers may relate to something like the position at which the number is displayed on the monitors in the control room.  I doubt that the GSOP would have any insight on that topic.  If that were the case, it wouldn't be surprising if it were covered in a different document, though at the moment I can't say I have a clue which one that would be.

**Comment by jumpjack** [comment] 2022-01-25 12:07
@rburkey2005 No I didn't receive your message neither by email.... Indeed I was going to write you directly, looking for help: do you think it would be possible to re-scan the document with better quality, to allow OCR?

**Comment by rburkey2005** [comment] 2022-01-25 12:27
No.  I'm afraid that the document has been scanned for the last time, and is as perfect as human technology allows.  It would have to be sent to a lab for a Shroud-of-Turin kind of analysis to get better results.  

The most perfect scan we're going to get is the one at our Internet Archive site that @thewonderidiot linked.  From there, you can download the original scanned images (https://archive.org/download/apollo_11_computer_words/apollo_11_computer_words_images.zip), as opposed to the crummier PDF.  Then, if you have image-processing software like GIMP or (presumably) Photoshop, you might be able to play around with various transformations like contrast adjustments, brightness, and so on that could conceivably make problematic areas more legible.

**Comment by rburkey2005** [comment] 2022-01-25 12:39
I mean, to give you some clue, the PDF is 5MB, while the original imagery is 623MB.  That should give you some idea of the quality difference.  Alas, little of that difference is visible to the naked eye, which is why additional legible detail, if any, would need image processing.  To make the PDF, some suitable overall settings needed to be chosen, whereas by applying different processing to specific problematic areas of images, detail that was invisible under the overall settings might be revealed.  I'm curious enough to experiment a little myself, and I'll comment later about whatever I find out.

With all that said, though, the document was simply very crummy to begin with.  50 years of storage hadn't been kind to it.

**Comment by jumpjack** [comment] 2022-01-25 13:05
Thanks.
I found a better starting pont than a 600MB file: the single files list:

https://ia902308.us.archive.org/view_archive.php?archive=/27/items/apollo_11_computer_words/apollo_11_computer_words_jp2.zip

First page:
https://ia802308.us.archive.org/view_archive.php?archive=/27/items/apollo_11_computer_words/apollo_11_computer_words_images.zip&file=apollo_11_computer_words_000.jp2&ext=jpg

https://archive.org/download/apollo_11_computer_words/apollo_11_computer_words_jp2.zip/apollo_11_computer_words_jp2%2Fapollo_11_computer_words_0000.jp2

JP2 version of same page is 7MB vs 300 KB!

I'll give it a try with IrfanView and XNView.

**Comment by rburkey2005** [comment] 2022-01-25 13:17
I think you mean "smaller" and not "better".  The zipfile you've linked to is a degraded JPEG2000 version of the original JPEG2000 imagery I linked.  If truly you want the best available quality, you need to start with the version I linked.

I tried some experimenting (on the version I linked), and found I could get some small improvements in legibility.  But admittedly, my skill level is nil.  If the behavior of movie and TV nerds is any guide, I'm sure other folks can do a much better job of enhancing it than I was able to.

**Comment by jumpjack** [comment] 2022-01-25 13:19
No, I mean that Ican access single files of the archive rather than downloading entire archive:
![immagine](https://user-images.githubusercontent.com/1620953/150984222-62b08687-1665-45c8-915b-31d042cb1023.png)

**Comment by thewonderidiot** [comment] 2022-01-25 17:07
Indeed, what you see in this scan is what you can see on the real copy. I scanned it at the best possible settings to try to pull out as much detail from it as I could. The paper is in fine condition -- it's just a bad scan of information that exists on film (where the quality may or may not be better). I believe that the film that this was scanned from is also in Don Eyles's collection, although I neglected to take a picture of it, and I am hoping to be able to fully digitize it at some point.

As for correlating elements to word numbers -- I think Ron is right, and the element number is most likely something to do with ground displays. I just went off of the column name and description.

**Comment by rburkey2005** [comment] 2022-01-25 17:18
What kind of film? Spools? Is there more film?

**Comment by thewonderidiot** [comment] 2022-01-25 18:17
It was one roll of film in an approximately 2.5" x 2.5" x 2.5" box -- and that's all I've got. Hence my regret for not taking pictures. I'll email Don and ask him if he knows any more about it.

**Comment by rburkey2005** [comment] 2022-01-25 18:29
No particular need.  I don't know if I recall talking about it or not, but I had acquired a film scanner a few years back.  But where that scanner would really be useful is in bulk, like for spools of microfilm, since it could scan whole spools automatically.  For this small amount of material, it wouldn't be practical to ship the machine to Boston, since it's huge and bulky and really heavy. Plus, I hate the machine and the manufacturer and the software and the user interface, and basically everything about it, and wouldn't want to inflict it on you anyway.

**Comment by jumpjack** [comment] 2022-01-25 22:05
Found another interesting log here: Apollo 11 simulation, performed in 1971 (???)

https://archive.org/details/dianarev12level302eyle

PDF compression destroyed almost everything:

![image](https://user-images.githubusercontent.com/1620953/151067315-48e8d15b-bd53-4a16-851f-922fca912991.png)

 but [original JP2 files ](https://ia801602.us.archive.org/view_archive.php?archive=/25/items/dianarev12level302eyle/dianarev12level302eyle_orig_jp2.tar) are very readable:

![image](https://user-images.githubusercontent.com/1620953/151067348-c3fd2814-3efd-445e-9368-ba46139fbca9.png)

**Comment by rburkey2005** [comment] 2022-01-25 23:26
Thanks!  I'm changing the document-library entry on the Virtual AGC website to use the archive.org copy as the preferred version, and removing the PDF link entirely.

**Comment by jumpjack** [comment] 2022-01-28 07:30
I am in trouble interpreting correctly the meaning of the log during the 120x alarms: documentation about AGC verbs and nouns changes from one version to another, it looks like for some absurd reasons  they assigned different tasks to same noun/verb couple in different missions, or more probably they exists different versions of same document and I can't distinguish which is the right one.

Does v1n68 mean range/tgo/velocity on LM-5?
But what about the v50n90 couple? Is it an user input or a computer output? How do I distinguish them in the log?

Then we have the famous v57e command, but what about the following v0n63 and v16n0?

This is the full sequence for the first 1202 (verb/noun):

- 6/63 Nominal
- 6/63 Nominal
- 16/0 ?? V16E followed by N68? Or the  N68 pressed more than 2 seconds after V16?
- 16/68 User query (for what?)
- 16/68
- 16/68
- 16/68
- 16/68
- 16/68
- 6/63 Nominal
- 50/63 ?? V50 is Input or output?
- 50/90 1202 -  V50N90 Input or output?      
- 50/90 1202
- 50/90 1202
- 50/90 1202
- 50/90 1202
- 50/90 1202
- 6/63 Nominal
- 6/63 Nominal
- 57/63 V57E - Accept Radar Updates
- 6/63 Nominal
- 0/63 ??

**Comment by rburkey2005** [comment] 2022-01-28 10:49
@jumpjack I guess I probably should have pointed out that what these GitHub "issues" are really intended for is reporting problems with the material stored in the GitHub repository.  In other words, for stuff in the repository that is broken and needs to be fixed somehow.  In the case of Virtual AGC's repository, that includes bugs in the Virtual AGC software, typos in transcriptions of AGC software, mistakes in the Virtual AGC website, etc.

But it's not a forum for answering general questions about the AGC or how to interpret its 50+ year old documentation.  I think you'd be better served by joining [the Virtual AGC mailing list](http://lists.ibiblio.org/mailman/listinfo/apollo) (if you haven't done so already) and submitting these kinds of questions there.  It's true that the same people who have been responding to your questions here may end up responding there, but there will be a lot of other eyes on your questions there than here. 

At any rate, this issue doesn't involve anything to fix, so I'm closing it.  Of course, you can still continue the conversation here, if you choose, even after the issue is closed, but in general it's just not going to be an efficient way to get such questions answered.

**Closed by rburkey2005** 2022-01-28 10:49 UTC

**Comment by jumpjack** [comment] 2022-01-28 11:56
A mailing list in 2022????

**Comment by jumpjack** [comment] 2022-01-28 13:28
With the help of [this VirtualAGC file](https://virtualagc.github.io/virtualagc/listings/Luminary099/FLAGWORD_ASSIGNMENTS.agc.html) I was able to decode all the unreadable headers from page 43 to 48 about FLAGWORDS status (FLAGWORD 13 is named "DAPBOOLS"):


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/LUCA~1.CAS/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/LUCA~1.CAS/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



  | FLAGWORD0 | FLAGWORD1 | FLAGWORD2 | FLAGWORD3 | FLAGWORD4 | FLAGWORD5 | FLAGWORD6 | FLAGWORD7 | FLAGWORD8 | FLAGWORD9 | FLAGWORD10 | FLAGWORD11 | FLAGWORD12 | FLAGWORD13
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | OLDESBIT | ==SPARE== | NODOBIT | DIMOBIT | XDSPBIT | RENDWBIT | ATTFLBIT | TFFSWBIT | 360SWBIT | AVEMDBIT | ==SPARE== | HFLSHBIT | ==SPARE== | AUTRATE1
2 | R10FLBIT | GUESSBIT | CALC2BIT | D6OR9BIT | ==SPARE== | MGLVFBIT | AUXFLBIT | V82EMBIT | INITABIT | MIDAVBIT | ==SPARE== | VFLSHBIT | ==SPARE== | AUTRATE2
3 | FREEFBIT | SLOPEBIT | CALC3BIT | VINTFBIT | MKOVBIT | SOLNSBIT | NTARGBIT | VERIFBIT | ==SPARE== | MID1BIT | ==SPARE== | SCABBIT | ==SPARE== | ACCSOKAY
4 | NEEDLBIT | ==SPARE== | PFRATBIT | INTYPBIT | NRUPTBIT | NORRMBIT | ==SPARE== | UPLOCBIT | COGAFBIT | ==SPARE== | ==SPARE== | RNGEDBIT | ==SPARE== | DBSELECT
5 | LOKONBIT | TRACKBIT | AVFLBIT | STATEBIT | MRUPTBIT | ==SPARE== | ==SPARE== | AVEGFBIT | APSESBIT | QUITBIT | ==SPARE== | READVBIT | ==SPARE== | AORBSYST
6 | RRNBBIT | NOUPFBIT | FINALBIT | ORBWFBIT | PINBRBIT | 3AXISBIT | REDFLBIT | V37FLBIT | ORDERBIT | ROTFLBIT | ==SPARE== | READLBIT | ==SPARE== | ULLAGER
7 | RNDVZBIT | UPDATBIT | ETPIBIT | CULTBIT | PRONVBIT | ENGONBIT | ==SPARE== | IDLEFBIT | INFINBIT | ==SPARE== | REINTBIT | VELDABIT | ==SPARE== | RHCSCALE
8 | IMUSEBIT | VEHUPBIT | XDELVBIT | PRECIBIT | NRMNVBIT | ==SPARE== | MUNFLBIT | V67FLBIT | SURFFBIT | FLAPBIT | ==SPARE== | LRINHBIT | ==SPARE== | DRIFTBIT
9 | P25FLBIT | ==SPARE== | IMPULBIT | READRBIT | MRKNVBIT | DMENFBIT | ==SPARE== | RVSWBIT | P39SWBIT | LETABBIT | ==SPARE== | XORFLBIT | ==SPARE== | XOVINHIB
A | FSPASBIT | R61FLBIT | ==SPARE== | VFLAGBIT | NWAITBIT | RNGSCBIT | GMBDRBIT | NORMSBIT | FLUNDBIT | FLRCSBIT | ==SPARE== | NOLRRBIT | ==SPARE== | AORBTRAN
B | P21FLBIT | ==SPARE== | STEERBIT | NR29FBIT | MWAITBIT | R77FLBIT | ==SPARE== | SWANDBIT | LMOONBIT | FLPIBIT | ==SPARE== | PSTHIBIT | ==SPARE== | ACC4OR2X
C | MOONBIT | RODFLBIT | LOSCMBIT | LUNABIT | PDSPFBIT | NOTHRBIT | S32BIT3B | ASTNBIT | CMOONBIT | FLPCBIT | ==SPARE== | VXINHBIT | ==SPARE== | OURRCBIT
D | MIDFLBIT | ERADFBIT | ACMODBIT | REFSMBIT | NRMIDBIT | SNUFFBIT | S32BIT3A | IGNFLBIT | NEWIBIT | ==SPARE== | APSFLBIT | ==SPARE== | ==SPARE== | CSMDOCKD
E | JSWCHBIT | PRIODBIT | SRCHOBIT | GLOKFBIT | ==SPARE== | ==SPARE== | S32BIT2 | MANUFBIT | ==SPARE== | FLVRBIT | INTFLBIT | ==SPARE== | ==SPARE== | USEQRJTS
F | ==SPARE== | ==SPARE== | DRFTBIT | ==SPARE== | MRKIDBIT | DSKYFBIT | S32BIT1 | ITSWBIT | RPQFLBIT | ==SPARE== | ==SPARE== | LRBYBIT | ==SPARE== | PULSES
Page | 43 | 43 | 43 | 43 | 44-45 | 44-45 | 44-45 | 44-45 | 47-48 | 47-48 | 47-48 | 47-48 | 49-52 | 49-52



</body>

</html>

**Comment by rburkey2005** [comment] 2022-01-28 13:35
> A mailing list in 2022????

I guess there's some more modern alternative that all the cool kids are using these days?

**Comment by jumpjack** [comment] 2022-01-28 13:36
> > A mailing list in 2022????
> 
> I guess there's some more modern alternative that all the cool kids are using these days?

PHPbb forums prevent mailboxes from being overwhelmed by thousands of emails coming  from dozens of mailing lists.

**Comment by jumpjack** [comment] 2022-01-28 13:37
This guy did set up a discussion forum on github itself, but I don't know how:

https://github.com/ImageMagick/ImageMagick/discussions

**Comment by rburkey2005** [comment] 2022-01-28 13:39
> With the help of [this VirtualAGC file](https://virtualagc.github.io/virtualagc/listings/Luminary099/FLAGWORD_ASSIGNMENTS.agc.html) I was able to decode all the unreadable headers from page 43 to 52 about FLAGWORDS status

What I'll do with this is to add a comment on the "document library" web page that links to this issue as containing assistance in decoding the document, so if you want to keep posting whatever progress you're making here, anyone who's concerned with the document would presumably see it.

**Comment by rburkey2005** [comment] 2022-01-28 13:41
> PHPbb forums prevent mailboxes from being overwhelmed by thousands of emails coming from dozens of mailing lists.

I think you may overestimate the overwhelmingness of the volume of discussions about the AGC.  :smile:

**Comment by rburkey2005** [comment] 2022-01-28 15:05
> This guy did set up a discussion forum on github itself, but I don't know how

This actually seems like a great idea.  It's easy to set up, and I've sent out a mailing to the mailing list calling their attention to it.

**Comment by jumpjack** [comment] 2022-01-30 10:03
Does anybody have an idea if DSKY  "LEDs" status is available in the telemetries?
And what about pitch, roll and yaw?

The PDF contains, apart from the 13 flagwords and the 3 registers:

P.12-13:
- TLRRNG
- LRRNG
- CDUYLRR
- CDUZLRR

P.14:

- TTF/8
- DELTAH
- LSVECX
- LSVECY
- LSVECZ
- LSPOX
- LSPOSY
- LSPOSZ

P.15-23:
- TLAND   
- DDPSTHR    
- VTHACCEL   
- TTOGO    
- CMDECA    

P.34-30:
- FAILREG 0, 1 ,2   
- RSBBQ 0,1,2
- CADRELSH 0,1,2

P.53-69
- CDUX (ACTUAL) 
- CDUDX (DESIRED)
- CDUY
- CDUDY 
- CDUZ
- CDUDZ
- RR CDUS (RR SHAFT CDU ANGLE) -  (RR SHAFT ANGLE, DP, IN REVOLUTIONS, SCALED B0)
- RR CDUT (RR TRUN CDU ANGLE)  (THE RR TRUNNION ANGLE, DP, IN REVOLUTIONS, SCALED B0)

**Comment by rburkey2005** [comment] 2022-01-30 15:47
The DSKY has no LEDs.  I presume you mean the array of indicator lamps on the upper left.

I'm not sure if it has been mentioned, and am too lazy to read back through these comments to find out, but the ultimate, guaranteed 100% accurate reference for the telemetry downlists is the AGC source code.  In the case of LM-5, [this file](http://www.ibiblio.org/apollo/listings/Luminary099/DOWNLINK_LISTS.agc.html).

Several of the downlists include DSPTAB, which is a 12-word buffer of what's displayed on the DSKY, including (I believe) the indicator lamps.  You may have to dig a bit to find out what appears where in that buffer.

**Comment by jumpjack** [comment] 2022-01-30 15:52
Thanks, yes by "LEDs" I meant the lamps... :-)

Yes I know that file but it's hard to find matches with the PDF, so I am looking for help.

**Comment by jumpjack** [comment] 2022-02-01 09:22
> ![image](https://user-images.githubusercontent.com/94056/150934298-19c84de6-1016-4441-91d6-5cab0cf626e9.png)
> 
> The last two columns start with CDUYLRR and CDUZLRR. (for "CDU Landing Radar Range) The variables in question are MKTIME, HMEAS, LRYCDUDL, and LRZCDUDL.

I am not very sure about how to interpret these values. If "LR" is for "Landing Radar", then what is the "T" for in "TLRRNG" ?  (xxx Landing Radar Range)
"TM" stands for "Telemetry" or something else?

And what about "DP" in second column? It is mentioned very often in the code; most of the times it means "Double Precision", but there is also another meaning which I do not get; "DPS" is Descent Propulsion System, but DP? 

-----

Another question is about DSPTAB: is it also called DAPTAB? (is it a typo?) It's definitely an "A" at page 46 of the PDF:
![image](https://user-images.githubusercontent.com/1620953/151938217-5665d12e-d504-406a-8b1f-d2589a42a0dd.png)

There is no "DAPTAB" in the source code, but there are many "DSPTAB+11d" occurrences.

-----

In the meantime, I found all the reference to DSKY lamps! :-)

Left column:

- **UPLINK ACTY**: "UPLINK ACTIV" in CHANNEL11 (p.34-42)
- **NO ATT**: "NO ATTITUDE" in DAPTAB+11d (pag.46)
- **STBY**: "ENABLE STDBY"  in CHANNEL13 (p.34-42)
- **KEY REL**: "RELEASE"  in CHANNEL11 (p.34-42)
- **OPR ERR**: "OPERATOR ERR"  in CHANNEL11 (p.34-42)


Right Column:
- **TEMP**: "TEMP CAUTION"  in CHANNEL11 (p.34-42)
- **GIMBAL LOCK**: "GIMBAL LOCK"  in DAPTAB+11d (pag.46)
- **PROG**: "PROG CAUTION"  in DAPTAB+11d (pag.46)
- **RESTART**: **not found yet**
- **TRACKER**: "TRACKER ALARM"  in DAPTAB+11d (pag.46)
- **ALT**: "HFLSHFLG" in FLAGWRD11, p.47-48 ("height flash flag")
- **VEL**: "VFLSHFLG"  in FLAGWRD11, p.47-48 ("velocity flash flag")

Others:

- "**COMP ACTY**" lamp: "COMP ACTIV"  in CHANNEL11 (p.34-42)
- **Verb and noun flashing** (=input required): "FL VERB NOUN"   in CHANNEL11 (p.34-42)
- "PRO"(ceed) key pressed: "PROCEED KEY" in CHANNEL32 (p.31-33) ("1" followed by "0" after each 1201/1202 alarm)

**Comment by jumpjack** [comment] 2022-02-01 15:21
I continue here...
https://github.com/jumpjack/dskysim/wiki/Decoding-AGC-telemetries
